In [235]:
import glob
csv_files = (glob.glob("C:/Users/Vishnu Kumar/Documents/IPL/raw/*info.csv"))

In [236]:
import pandas as pd


df_append = pd.DataFrame()

for file in csv_files:
            df_temp = pd.read_csv(file,sep='漢ழ்字', engine='python',header=None)
            df_temp['ID'] = file
            df_temp = df_temp[(df_temp[0].str.startswith('info,toss_winner')) | (df_temp[0].str.startswith('info,toss_decision'))]
            df_append = pd.concat([df_append,df_temp])

df_append = df_append.reset_index()
df_append[['info', 'attrib','value']] = df_append[0].str.split(",", expand = True)
df_append = df_append.drop(columns=['index',0,'info'])
df_append['ID'] = df_append['ID'].str[40:-9]
toss_winner = df_append[df_append['attrib']=='toss_winner']
toss_decision = df_append[df_append['attrib']=='toss_decision']
toss_winner['ID'] = toss_winner['ID'].astype('int')
toss_decision['ID'] = toss_decision['ID'].astype('int')

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_1776\369246093.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  toss_winner['ID'] = toss_winner['ID'].astype('int')
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_1776\369246093.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  toss_decision['ID'] = toss_decision['ID'].astype('int')

In [262]:
all_matches = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")
# all_matches
all_matches = pd.merge(all_matches, toss_winner, how="left" ,left_on = "match_id", right_on = "ID" )
all_matches = all_matches.drop(columns=["ID", "attrib"])
all_matches = all_matches.rename(columns={"value": "toss_winner"})
all_matches = pd.merge(all_matches, toss_decision, how="left" ,left_on = "match_id", right_on = "ID" )
all_matches = all_matches.drop(columns=["ID", "attrib"])
all_matches = all_matches.rename(columns={"value": "toss_decision"})
# all_matches = pd.concat([all_matches, toss_winner], axis=1, join='outer', join_axes=[match_id,ID])

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_1776\2599081134.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  all_matches = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")

In [263]:
all_matches['season'] = all_matches['season'].replace(['2007/08', '2009', '2009/10', '2011' ,'2012','2018', '2019', '2020/21', '2021'], [2008,2009,2010,2011,2012,2018,2019,2020,2021])

In [264]:
venue = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\venue.xlsx")
all_matches = pd.merge(all_matches, venue, how="left" ,left_on = "venue", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","Bit"])
# all_matches

In [265]:
all_matches['ball'] = (all_matches['ball'].astype('int')*6)+((all_matches['ball'] - all_matches['ball'].astype('int'))*10)

In [266]:
team = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\team.xlsx")
all_matches = pd.merge(all_matches, team, how="left" ,left_on = "batting_team", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","Bit"])
# all_matches

In [267]:
team2 = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\team2.xlsx")
all_matches = pd.merge(all_matches, team2, how="left" ,left_on = "bowling_team", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","Bit"])
# all_matches

In [268]:
player = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\player.xlsx")
player = player.rename(columns={"player1": "striker1","player2": "striker2","player3": "striker3","player4": "striker4","player5": "striker5","player6": "striker6","player7": "striker7","player8": "striker8","player9": "striker9","player10": "striker10"})
all_matches = pd.merge(all_matches, player, how="left" ,left_on = "striker", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","bit"])
# all_matches

In [269]:
player = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\player.xlsx")
player = player.rename(columns={"player1": "non_striker1","player2": "non_striker2","player3": "non_striker3","player4": "non_striker4","player5": "non_striker5","player6": "non_striker6","player7": "non_striker7","player8": "non_striker8","player9": "non_striker9","player10": "non_striker10"})
all_matches = pd.merge(all_matches, player, how="left" ,left_on = "non_striker", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","bit"])
# all_matches

In [270]:
player = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\player.xlsx")
player = player.rename(columns={"player1": "bowler1","player2": "bowler2","player3": "bowler3","player4": "bowler4","player5": "bowler5","player6": "bowler6","player7": "bowler7","player8": "bowler8","player9": "bowler9","player10": "bowler10"})
all_matches = pd.merge(all_matches, player, how="left" ,left_on = "non_striker", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","bit"])
# all_matches

In [271]:
wicket = pd.read_excel(r"C:\Users\Vishnu Kumar\Documents\IPL\LU\wicket.xlsx")
# player = player.rename(columns={"player1": "bowler1","player2": "bowler2","player3": "bowler3","player4": "bowler4","player5": "bowler5","player6": "bowler6","player7": "bowler7","player8": "bowler8","player9": "bowler9","player10": "bowler10"})
all_matches = pd.merge(all_matches, wicket, how="left" ,left_on = "wicket_type", right_on = "key" )
all_matches = all_matches.drop(columns=["key", "filter name","bit"])
# all_matches

In [272]:
all_matches['toss_win_batting'] = all_matches.apply(lambda x: 1 if x['toss_winner'] == x['batting_team'] else 0, axis=1)
# all_matches

In [273]:
all_matches['toss_decision'] = all_matches.apply(lambda x: 1 if x['toss_decision'] == 'bat' else 0, axis=1)
# all_matches

In [274]:
all_matches['player_dismissed'] = all_matches.apply(lambda x: 1 if x['player_dismissed'] == x['striker'] else 0, axis=1)
# all_matches['player_dismissed']

In [275]:
all_matches['wic'] = 0
for index,row in all_matches.iterrows():
    temp = all_matches[(all_matches['match_id']==all_matches['match_id'][index]) & (all_matches['innings']==all_matches['innings'][index]) & (all_matches['ball']<all_matches['ball'][index])]
    all_matches['wic'][index] = temp['wicket_type'].count()

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_1776\105967443.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches['wic'][index] = temp['wicket_type'].count()

In [276]:
all_matches = all_matches.fillna(0)

In [277]:
all_matches['target'] = 0
for index,row in all_matches.iterrows():
    if all_matches['innings'][index]==2:
        temp = all_matches[(all_matches['match_id']==all_matches['match_id'][index]) & (all_matches['innings']==1)]
        all_matches['target'][index] = temp['runs_off_bat'].sum()+temp['extras'].sum()

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_1776\395309427.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_matches['target'][index] = temp['runs_off_bat'].sum()+temp['extras'].sum()

In [278]:
all_matches['byes'] = all_matches['byes'] + all_matches['legbyes']
all_matches['extras'] = all_matches['extras'] - all_matches['byes']

In [279]:
all_matches.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 225954 entries, 0 to 225953
Data columns (total 75 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                225954 non-null  int64
 1   season                  225954 non-null  int64
 2   start_date              225954 non-null  object
 3   venue                   225954 non-null  object
 4   innings                 225954 non-null  int64
 5   ball                    225954 non-null  float64
 6   batting_team            225954 non-null  object
 7   bowling_team            225954 non-null  object
 8   striker                 225954 non-null  object
 9   non_striker             225954 non-null  object
 10  bowler                  225954 non-null  object
 11  runs_off_bat            225954 non-null  int64
 12  extras                  225954 non-null  float64
 13  wides                   225954 non-null  float64
 14  noballs                 225954 non-null  float64
 15  byes                    225954 non-null  float64
 16  legbyes                 225954 non-null  float64
 17  penalty                 225954 non-null  float64
 18  wicket_type             225954 non-null  object
 19  player_dismissed        225954 non-null  int64
 20  other_wicket_type       225954 non-null  float64
 21  other_player_dismissed  225954 non-null  float64
 22  toss_winner             225954 non-null  object
 23  toss_decision           225954 non-null  int64
 24  Venue1                  225954 non-null  float64
 25  Venue2                  225954 non-null  float64
 26  Venue3                  225954 non-null  float64
 27  Venue4                  225954 non-null  float64
 28  Venue5                  225954 non-null  float64
 29  Venue6                  225954 non-null  float64
 30  batting_team1           225954 non-null  int64
 31  batting_team2           225954 non-null  int64
 32  batting_team3           225954 non-null  int64
 33  batting_team4           225954 non-null  int64
 34  bowling_team1           225954 non-null  int64
 35  bowling_team2           225954 non-null  int64
 36  bowling_team3           225954 non-null  int64
 37  bowling_team4           225954 non-null  int64
 38  striker1                225954 non-null  int64
 39  striker2                225954 non-null  int64
 40  striker3                225954 non-null  int64
 41  striker4                225954 non-null  int64
 42  striker5                225954 non-null  int64
 43  striker6                225954 non-null  int64
 44  striker7                225954 non-null  int64
 45  striker8                225954 non-null  int64
 46  striker9                225954 non-null  int64
 47  striker10               225954 non-null  int64
 48  non_striker1            225954 non-null  int64
 49  non_striker2            225954 non-null  int64
 50  non_striker3            225954 non-null  int64
 51  non_striker4            225954 non-null  int64
 52  non_striker5            225954 non-null  int64
 53  non_striker6            225954 non-null  int64
 54  non_striker7            225954 non-null  int64
 55  non_striker8            225954 non-null  int64
 56  non_striker9            225954 non-null  int64
 57  non_striker10           225954 non-null  int64
 58  bowler1                 225954 non-null  int64
 59  bowler2                 225954 non-null  int64
 60  bowler3                 225954 non-null  int64
 61  bowler4                 225954 non-null  int64
 62  bowler5                 225954 non-null  int64
 63  bowler6                 225954 non-null  int64
 64  bowler7                 225954 non-null  int64
 65  bowler8                 225954 non-null  int64
 66  bowler9                 225954 non-null  int64
 67  bowler10                225954 non-null  int64
 68  wicket1                 225954 non-null  float64
 69  wicket2                 225954 non-null  float64
 70  wicket3                 225954 non-null  float64
 71  wicket4                 225954 non-null  float64
 72  toss_win_batting        225954 non-null  int64
 73  wic                     225954 non-null  int64
 74  target                  225954 non-null  int64
dtypes: float64(19), int64(47), object(9)
memory usage: 139.1+ MB

In [280]:
all_matches

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,bowler8,bowler9,bowler10,wicket1,wicket2,wicket3,wicket4,toss_win_batting,wic,target
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,1.0,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,0,0,1,0.0,0.0,0.0,0.0,0,0,0
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,2.0,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,1,1,0.0,0.0,0.0,0.0,0,0,0
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,3.0,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,1,1,0.0,0.0,0.0,0.0,0,0,0
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,4.0,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,1,1,0.0,0.0,0.0,0.0,0,0,0
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,5.0,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,1,1,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,1312200,2022,2022-05-29,"Narendra Modi Stadium, Ahmedabad",2,105.0,Gujarat Titans,Rajasthan Royals,DA Miller,Shubman Gill,...,0,1,1,0.0,0.0,0.0,0.0,0,3,130
225950,1312200,2022,2022-05-29,"Narendra Modi Stadium, Ahmedabad",2,106.0,Gujarat Titans,Rajasthan Royals,Shubman Gill,DA Miller,...,1,0,1,0.0,0.0,0.0,0.0,0,3,130
225951,1312200,2022,2022-05-29,"Narendra Modi Stadium, Ahmedabad",2,107.0,Gujarat Titans,Rajasthan Royals,Shubman Gill,DA Miller,...,1,0,1,0.0,0.0,0.0,0.0,0,3,130
225952,1312200,2022,2022-05-29,"Narendra Modi Stadium, Ahmedabad",2,108.0,Gujarat Titans,Rajasthan Royals,DA Miller,Shubman Gill,...,0,1,1,0.0,0.0,0.0,0.0,0,3,130
225953,1312200,2022,2022-05-29,"Narendra Modi Stadium, Ahmedabad",2,109.0,Gujarat Titans,Rajasthan Royals,Shubman Gill,DA Miller,...,1,0,1,0.0,0.0,0.0,0.0,0,3,130

In [281]:
all_matches = all_matches.drop(columns=['venue','match_id','start_date','batting_team','bowling_team','striker','non_striker','bowler','wides','noballs','legbyes','penalty','wicket_type','other_wicket_type','other_player_dismissed','toss_winner'])

In [124]:
all_matches.wicket_type.drop_duplicates()

0                           NaN
33                       caught
131                      bowled
197                     run out
269                         lbw
954                retired hurt
1035                    stumped
1109          caught and bowled
2358                 hit wicket
92241     obstructing the field
212754              retired out
Name: wicket_type, dtype: object

In [282]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, BatchNormalization, Dropout

# Load the cricket data into a Pandas DataFrame
df = all_matches.copy()

# Split the data into input features and output variables
X = df.drop(['runs_off_bat', 'extras','byes','player_dismissed','wicket1','wicket2','wicket3','wicket4','non_striker1','non_striker2','non_striker3','non_striker4','non_striker5','non_striker6','non_striker7','non_striker8','non_striker9','non_striker10'], axis=1)
y = df[['runs_off_bat', 'extras','byes','player_dismissed','wicket1','wicket2','wicket3','wicket4']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalize the input data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the model architecture
model = Sequential()
model.add(Dense(64, input_shape=(X_train.shape[1],), activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Dense(8, activation='linear'))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(X_train_scaled, y_train, epochs=50, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluate the model
score = model.evaluate(X_test_scaled, y_test)
print('Test loss:', score)

Epoch 1/50
5649/5649 [==============================] - 16s 3ms/step - loss: 0.3980 - val_loss: 0.3470
Epoch 2/50
5649/5649 [==============================] - 14s 2ms/step - loss: 0.3469 - val_loss: 0.3458
Epoch 3/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3458 - val_loss: 0.3452
Epoch 4/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3451 - val_loss: 0.3446
Epoch 5/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3447 - val_loss: 0.3449
Epoch 6/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3443 - val_loss: 0.3447
Epoch 7/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3441 - val_loss: 0.3445
Epoch 8/50
5649/5649 [==============================] - 14s 2ms/step - loss: 0.3440 - val_loss: 0.3443
Epoch 9/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3435 - val_loss: 0.3456
Epoch 10/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3433 - val_loss: 0.3448
Epoch 11/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3435 - val_loss: 0.3447
Epoch 12/50
5649/5649 [==============================] - 14s 2ms/step - loss: 0.3432 - val_loss: 0.3447
Epoch 13/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3429 - val_loss: 0.3448
Epoch 14/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3427 - val_loss: 0.3448
Epoch 15/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3429 - val_loss: 0.3446
Epoch 16/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3427 - val_loss: 0.3450
Epoch 17/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3428 - val_loss: 0.3444
Epoch 18/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3424 - val_loss: 0.3444
Epoch 19/50
5649/5649 [==============================] - 14s 2ms/step - loss: 0.3425 - val_loss: 0.3445
Epoch 20/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3421 - val_loss: 0.3450
Epoch 21/50
5649/5649 [==============================] - 14s 2ms/step - loss: 0.3422 - val_loss: 0.3445
Epoch 22/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3420 - val_loss: 0.3450
Epoch 23/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3420 - val_loss: 0.3445
Epoch 24/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3419 - val_loss: 0.3447
Epoch 25/50
5649/5649 [==============================] - 19s 3ms/step - loss: 0.3419 - val_loss: 0.3446
Epoch 26/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3417 - val_loss: 0.3448
Epoch 27/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3418 - val_loss: 0.3446
Epoch 28/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3417 - val_loss: 0.3444
Epoch 29/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3416 - val_loss: 0.3451
Epoch 30/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3415 - val_loss: 0.3442
Epoch 31/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3415 - val_loss: 0.3444
Epoch 32/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3411 - val_loss: 0.3442
Epoch 33/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3414 - val_loss: 0.3446
Epoch 34/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3413 - val_loss: 0.3444
Epoch 35/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3414 - val_loss: 0.3447
Epoch 36/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3411 - val_loss: 0.3446
Epoch 37/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3408 - val_loss: 0.3449
Epoch 38/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3410 - val_loss: 0.3445
Epoch 39/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3409 - val_loss: 0.3445
Epoch 40/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3409 - val_loss: 0.3445
Epoch 41/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3410 - val_loss: 0.3445
Epoch 42/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3409 - val_loss: 0.3445
Epoch 43/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3408 - val_loss: 0.3444
Epoch 44/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3411 - val_loss: 0.3446
Epoch 45/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3412 - val_loss: 0.3444
Epoch 46/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3407 - val_loss: 0.3449
Epoch 47/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3409 - val_loss: 0.3446
Epoch 48/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3409 - val_loss: 0.3445
Epoch 49/50
5649/5649 [==============================] - 15s 3ms/step - loss: 0.3407 - val_loss: 0.3444
Epoch 50/50
5649/5649 [==============================] - 14s 3ms/step - loss: 0.3407 - val_loss: 0.3446
1413/1413 [==============================] - 2s 1ms/step - loss: 0.3446
Test loss: 0.34455570578575134

Venue,
Chinnaswamy Bangalore,
Bindra Mohali,
Feroz Delhi,
Eden Kolkata,
Wankhede Mumbai,
Mansingh Jaipur,
Rajiv Hyderabad,
Chidambaram Chennai,
Patil Mumbai,
Newlands SA,
George SA,
Kingsmead SA,
Supersport SA,
Buffalo SA,
Wanderers SA,
Beers SA,
Outsurance SA,
Brabourne Mumbai,
Sardar Ahmedabad,
Barabati Cuttack,
Brabourne Mumbai,
Vidarbha Nagpur,
HPCA Dharamshala,
Jawaharlal Kochi,
Holkar Indore,
Rajashekar Visakhapatnam,
Subrata Pune,
Subrata Pune,
Shaheed Raipur,
JSCA Ranchi,
Abudhabi UAE,
Sharjah UAE,
Dubai UAE,
Bindra Mohali,
Saurashtra Rajkot,
Green Kanpur,
Chinnaswamy Bangalore,
Chidambaram Chennai,
Feroz Delhi,
Rajiv Hyderabad,
Bindra Mohali,
Chidambaram Chennai,
Wankhede Mumbai,
Sardar Ahmedabad,
Feroz Delhi,
Abudhabi UAE,
Patil Mumbai,
Subrata Pune,
Eden Kolkata

Team,
Kolkata,
Bangalore,
Chennai,
Punjab,
Rajastan,
Delhi,
Hyderabad,
Mumbai,
Kochi,
Pune,
Hyderabad,
Pune,
Gujarat,
Pune,
Delhi,
Punjab,
Lucknow,
Gujarat

In [283]:
all_data = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_1776\3406251394.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  all_data = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")

In [173]:
season = 2023
innings = 1

# batting_team = 
# bowling_team = 
# striker = 
# bowler =
# toss_win_batting = 

ball = ['a','b','c']

for i in enumerate(ball):
    print(i)

# for ball in range(120):
#     print(ball)

(0, 'a')
(1, 'b')
(2, 'c')