In [161]:
import glob
import numpy as np
csv_files = (glob.glob("C:/Users/Vishnu Kumar/Documents/IPL/raw/*info.csv"))

In [162]:
import pandas as pd


df_append = pd.DataFrame()

for file in csv_files:
            df_temp = pd.read_csv(file,sep='漢ழ்字', engine='python',header=None)
            df_temp['ID'] = file
            df_temp = df_temp[(df_temp[0].str.startswith('info,toss_winner')) | (df_temp[0].str.startswith('info,toss_decision'))]
            df_append = pd.concat([df_append,df_temp])

df_append = df_append.reset_index()
df_append[['info', 'attrib','value']] = df_append[0].str.split(",", expand = True)
df_append = df_append.drop(columns=['index',0,'info'])
df_append['ID'] = df_append['ID'].str[40:-9]
toss_winner = df_append[df_append['attrib']=='toss_winner'].copy()
toss_decision = df_append[df_append['attrib']=='toss_decision'].copy()
toss_winner['ID'] = toss_winner['ID'].astype('int')
toss_decision['ID'] = toss_decision['ID'].astype('int')

In [163]:
import pandas as pd


df_append = pd.DataFrame()

for file in csv_files:
            df_temp = pd.read_csv(file,sep='漢ழ்字', engine='python',header=None)
            df_temp['ID'] = file
            df_temp = df_temp[(df_temp[0].str.startswith('info,player,'))]
            df_append = pd.concat([df_append,df_temp])

df_append = df_append.reset_index()
df_append[['info', 'info2','team','player']] = df_append[0].str.split(",", expand = True)
df_append = df_append.drop(columns=['index',0,'info', 'info2',])
df_append['ID'] = df_append['ID'].str[40:-9]
df_append['ID'] = df_append['ID'].astype('int')
team_members = df_append.copy()

In [164]:
all_matches = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")
# all_matches
all_matches = pd.merge(all_matches, toss_winner, how="left" ,left_on = "match_id", right_on = "ID" )
all_matches = all_matches.drop(columns=["ID", "attrib"])
all_matches = all_matches.rename(columns={"value": "toss_winner"})
all_matches = pd.merge(all_matches, toss_decision, how="left" ,left_on = "match_id", right_on = "ID" )
all_matches = all_matches.drop(columns=["ID", "attrib"])
all_matches = all_matches.rename(columns={"value": "toss_decision"})
all_matches = all_matches[all_matches['innings']<=2]
all_matches['season'] = all_matches['season'].replace(['2007/08', '2009', '2009/10', '2011' ,'2012','2018', '2019', '2020/21', '2021'], [2008,2009,2010,2011,2012,2018,2019,2020,2021])
all_matches['toss_win_batting'] = all_matches.apply(lambda x: 1 if x['toss_winner'] == x['batting_team'] else 0, axis=1)
all_matches['toss_decision'] = all_matches.apply(lambda x: 1 if x['toss_decision'] == 'bat' else 0, axis=1)
all_matches['player_dismissed'] = all_matches.apply(lambda x: 1 if x['player_dismissed'] == x['striker'] else 0, axis=1)
all_data = all_matches.copy()
# all_matches = pd.concat([all_matches, toss_winner], axis=1, join='outer', join_axes=[match_id,ID])

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_6368\579395103.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  all_matches = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")

In [165]:
all_for_bowlers = all_data.copy()
all_for_bowlers['ball'] = (all_for_bowlers['ball'].apply(np.floor))+1
all_for_bowlers = all_for_bowlers.drop(columns=['start_date','striker','non_striker','runs_off_bat','extras','wides','noballs','byes','legbyes','penalty','wicket_type','player_dismissed','other_wicket_type','other_player_dismissed'])
all_for_bowlers['over_1'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 1 else 0, axis=1)
all_for_bowlers['over_2'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 2 else 0, axis=1)
all_for_bowlers['over_3'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 3 else 0, axis=1)
all_for_bowlers['over_4'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 4 else 0, axis=1)
all_for_bowlers['over_5'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 5 else 0, axis=1)
all_for_bowlers['over_6'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 6 else 0, axis=1)
all_for_bowlers['over_7'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 7 else 0, axis=1)
all_for_bowlers['over_8'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 8 else 0, axis=1)
all_for_bowlers['over_9'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 9 else 0, axis=1)
all_for_bowlers['over_10'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 10 else 0, axis=1)
all_for_bowlers['over_11'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 11 else 0, axis=1)
all_for_bowlers['over_12'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 12 else 0, axis=1)
all_for_bowlers['over_13'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 13 else 0, axis=1)
all_for_bowlers['over_14'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 14 else 0, axis=1)
all_for_bowlers['over_15'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 15 else 0, axis=1)
all_for_bowlers['over_16'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 16 else 0, axis=1)
all_for_bowlers['over_17'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 17 else 0, axis=1)
all_for_bowlers['over_18'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 18 else 0, axis=1)
all_for_bowlers['over_19'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 19 else 0, axis=1)
all_for_bowlers['over_20'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 20 else 0, axis=1)
# all_for_bowlers

In [166]:
all_for_bowlers = pd.pivot_table(all_for_bowlers, values =['over_1','over_2','over_3','over_4','over_5','over_6','over_7','over_8','over_9','over_10','over_11','over_12','over_13','over_14','over_15','over_16','over_17','over_18','over_19','over_20'], index =['match_id', 'season','venue','innings','batting_team','bowling_team','bowler','toss_winner','toss_decision','toss_win_batting'], aggfunc = np.max).reset_index()
all_for_bowlers = pd.pivot_table(all_for_bowlers, values=['over_1','over_2','over_3','over_4','over_5','over_6','over_7','over_8','over_9','over_10','over_11','over_12','over_13','over_14','over_15','over_16','over_17','over_18','over_19','over_20'], index=['match_id','venue','innings','bowler','batting_team','bowling_team'], aggfunc=np.sum).reset_index()

In [167]:
all_for_bowlers = all_for_bowlers.rename(columns={"match_id":"match number", "bowler": "bowler name","bowling_team" : "team name","batting_team": "opposite team name","innings":"bowling innings" })

In [168]:
# one-hot encode categorical features
team_members = pd.get_dummies(team_members, columns=['player'])

In [169]:
cols_to_normalize = team_members.columns[2:]
team_members = pd.pivot_table(team_members,values = cols_to_normalize, index=['ID','team'],aggfunc=np.sum).reset_index()

In [170]:
all_for_bowlers = pd.merge( all_for_bowlers, team_members, how="left" ,left_on = ['match number','team name'], right_on = ['ID','team'])

In [171]:
all_for_bowlers

,match number,venue,bowling innings,bowler name,opposite team name,team name,over_1,over_10,over_11,over_12,...,player_YA Abdulla,player_YBK Jaiswal,player_YK Pathan,player_YS Chahal,player_YV Takawale,player_Yash Dayal,player_Yashpal Singh,player_Younis Khan,player_Yuvraj Singh,player_Z Khan
0,335982,M Chinnaswamy Stadium,1,AA Noffke,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,335982,M Chinnaswamy Stadium,1,CL White,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,335982,M Chinnaswamy Stadium,1,JH Kallis,Kolkata Knight Riders,Royal Challengers Bangalore,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,335982,M Chinnaswamy Stadium,1,P Kumar,Kolkata Knight Riders,Royal Challengers Bangalore,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,335982,M Chinnaswamy Stadium,1,SB Joshi,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11218,1312200,"Narendra Modi Stadium, Ahmedabad",2,M Prasidh Krishna,Gujarat Titans,Rajasthan Royals,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0
11219,1312200,"Narendra Modi Stadium, Ahmedabad",2,OC McCoy,Gujarat Titans,Rajasthan Royals,0,0,1,0,...,0,1,0,1,0,0,0,0,0,0
11220,1312200,"Narendra Modi Stadium, Ahmedabad",2,R Ashwin,Gujarat Titans,Rajasthan Royals,0,0,0,1,...,0,1,0,1,0,0,0,0,0,0
11221,1312200,"Narendra Modi Stadium, Ahmedabad",2,TA Boult,Gujarat Titans,Rajasthan Royals,1,0,0,0,...,0,1,0,1,0,0,0,0,0,0
11222,1312200,"Narendra Modi Stadium, Ahmedabad",2,YS Chahal,Gujarat Titans,Rajasthan Royals,0,1,0,0,...,0,1,0,1,0,0,0,0,0,0

In [172]:
import pandas as pd
import numpy as np

# load the dataset
dataset = all_for_bowlers.copy()

# drop irrelevant columns
dataset = dataset.drop(columns=['match number', 'venue','ID','team','opposite team name','team name'])

# one-hot encode categorical features
dataset = pd.get_dummies(dataset, columns=['bowler name'])

# create a new feature for number of overs bowled by each bowler
# overs_cols = [f"over_{i}" for i in range(1, 21)]
# dataset['total_overs'] = dataset[overs_cols].sum(axis=1)

# create a binary feature for the bowling innings
dataset['bowling_innings'] = dataset['bowling innings'].apply(lambda x: 1 if x == 1 else 0)
dataset = dataset.drop(columns=['bowling innings','bowling_innings'])

# # normalize the data
# cols_to_normalize = dataset.columns[3:]
# dataset[cols_to_normalize] = (dataset[cols_to_normalize]-dataset[cols_to_normalize].min())/(dataset[cols_to_normalize].max()-dataset[cols_to_normalize].min())

# split the dataset into train and test sets
train_set = dataset.sample(frac=0.8, random_state=42)
test_set = dataset.drop(train_set.index)

# extract the features and labels
X_train = train_set.iloc[:, 20:].values
y_train = train_set.iloc[:, 0:20].values
X_test = test_set.iloc[:, 20:].values
y_test = test_set.iloc[:, 0:20].values

In [173]:
train_set.iloc[:, 20:]

,player_A Ashish Reddy,player_A Badoni,player_A Chandila,player_A Chopra,player_A Choudhary,player_A Dananjaya,player_A Flintoff,player_A Kumble,player_A Manohar,player_A Mishra,...,bowler name_Y Nagar,bowler name_Y Prithvi Raj,bowler name_Y Venugopal Rao,bowler name_YA Abdulla,bowler name_YBK Jaiswal,bowler name_YK Pathan,bowler name_YS Chahal,bowler name_Yash Dayal,bowler name_Yuvraj Singh,bowler name_Z Khan
9445,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
902,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10166,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5397,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1494,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8561,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11090,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4285,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6979,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [174]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy

# Define the model architecture
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(32, activation='relu'))
model.add(Dense(20, activation='sigmoid'))

# Compile the model
optimizer = Adam(learning_rate=0.001)
loss_fn = BinaryCrossentropy()
model.compile(optimizer=optimizer, loss=loss_fn)

# Train the model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
225/225 [==============================] - 1s 4ms/step - loss: 0.4820 - val_loss: 0.4456
Epoch 2/100
225/225 [==============================] - 1s 3ms/step - loss: 0.4397 - val_loss: 0.4397
Epoch 3/100
225/225 [==============================] - 1s 3ms/step - loss: 0.4233 - val_loss: 0.4247
Epoch 4/100
225/225 [==============================] - 1s 3ms/step - loss: 0.4078 - val_loss: 0.4213
Epoch 5/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3999 - val_loss: 0.4211
Epoch 6/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3937 - val_loss: 0.4214
Epoch 7/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3881 - val_loss: 0.4220
Epoch 8/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3825 - val_loss: 0.4225
Epoch 9/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3775 - val_loss: 0.4239
Epoch 10/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3725 - val_loss: 0.4269
Epoch 11/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3677 - val_loss: 0.4298
Epoch 12/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3630 - val_loss: 0.4341
Epoch 13/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3586 - val_loss: 0.4362
Epoch 14/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3544 - val_loss: 0.4419
Epoch 15/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3500 - val_loss: 0.4460
Epoch 16/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3455 - val_loss: 0.4528
Epoch 17/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3418 - val_loss: 0.4543
Epoch 18/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3373 - val_loss: 0.4626
Epoch 19/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3337 - val_loss: 0.4653
Epoch 20/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3297 - val_loss: 0.4691
Epoch 21/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3256 - val_loss: 0.4788
Epoch 22/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3221 - val_loss: 0.4823
Epoch 23/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3183 - val_loss: 0.4864
Epoch 24/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3149 - val_loss: 0.4940
Epoch 25/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3113 - val_loss: 0.4994
Epoch 26/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3078 - val_loss: 0.5058
Epoch 27/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3042 - val_loss: 0.5106
Epoch 28/100
225/225 [==============================] - 1s 3ms/step - loss: 0.3010 - val_loss: 0.5160
Epoch 29/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2978 - val_loss: 0.5250
Epoch 30/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2942 - val_loss: 0.5283
Epoch 31/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2914 - val_loss: 0.5391
Epoch 32/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2884 - val_loss: 0.5413
Epoch 33/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2858 - val_loss: 0.5459
Epoch 34/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2828 - val_loss: 0.5558
Epoch 35/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2798 - val_loss: 0.5623
Epoch 36/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2769 - val_loss: 0.5701
Epoch 37/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2739 - val_loss: 0.5735
Epoch 38/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2714 - val_loss: 0.5818
Epoch 39/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2693 - val_loss: 0.5849
Epoch 40/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2665 - val_loss: 0.5934
Epoch 41/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2641 - val_loss: 0.5981
Epoch 42/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2613 - val_loss: 0.6079
Epoch 43/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2592 - val_loss: 0.6108
Epoch 44/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2569 - val_loss: 0.6169
Epoch 45/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2548 - val_loss: 0.6264
Epoch 46/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2524 - val_loss: 0.6287
Epoch 47/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2499 - val_loss: 0.6355
Epoch 48/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2477 - val_loss: 0.6473
Epoch 49/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2455 - val_loss: 0.6540
Epoch 50/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2434 - val_loss: 0.6623
Epoch 51/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2418 - val_loss: 0.6693
Epoch 52/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2395 - val_loss: 0.6724
Epoch 53/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2377 - val_loss: 0.6772
Epoch 54/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2358 - val_loss: 0.6829
Epoch 55/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2337 - val_loss: 0.6916
Epoch 56/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2320 - val_loss: 0.7017
Epoch 57/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2299 - val_loss: 0.7062
Epoch 58/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2285 - val_loss: 0.7159
Epoch 59/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2258 - val_loss: 0.7202
Epoch 60/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2250 - val_loss: 0.7284
Epoch 61/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2236 - val_loss: 0.7328
Epoch 62/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2211 - val_loss: 0.7438
Epoch 63/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2206 - val_loss: 0.7467
Epoch 64/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2181 - val_loss: 0.7571
Epoch 65/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2164 - val_loss: 0.7584
Epoch 66/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2151 - val_loss: 0.7713
Epoch 67/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2137 - val_loss: 0.7762
Epoch 68/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2124 - val_loss: 0.7840
Epoch 69/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2109 - val_loss: 0.7901
Epoch 70/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2096 - val_loss: 0.7941
Epoch 71/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2084 - val_loss: 0.8082
Epoch 72/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2064 - val_loss: 0.8108
Epoch 73/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2051 - val_loss: 0.8205
Epoch 74/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2039 - val_loss: 0.8222
Epoch 75/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2021 - val_loss: 0.8313
Epoch 76/100
225/225 [==============================] - 1s 3ms/step - loss: 0.2009 - val_loss: 0.8414
Epoch 77/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1998 - val_loss: 0.8426
Epoch 78/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1990 - val_loss: 0.8544
Epoch 79/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1974 - val_loss: 0.8589
Epoch 80/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1963 - val_loss: 0.8585
Epoch 81/100

225/225 [==============================] - 1s 3ms/step - loss: 0.1952 - val_loss: 0.8832
Epoch 82/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1938 - val_loss: 0.8782
Epoch 83/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1930 - val_loss: 0.8831
Epoch 84/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1918 - val_loss: 0.8952
Epoch 85/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1907 - val_loss: 0.9000
Epoch 86/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1896 - val_loss: 0.9075
Epoch 87/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1885 - val_loss: 0.9140
Epoch 88/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1876 - val_loss: 0.9239
Epoch 89/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1864 - val_loss: 0.9346
Epoch 90/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1849 - val_loss: 0.9388
Epoch 91/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1844 - val_loss: 0.9455
Epoch 92/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1835 - val_loss: 0.9511
Epoch 93/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1819 - val_loss: 0.9512
Epoch 94/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1813 - val_loss: 0.9572
Epoch 95/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1806 - val_loss: 0.9654
Epoch 96/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1798 - val_loss: 0.9780
Epoch 97/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1784 - val_loss: 0.9846
Epoch 98/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1772 - val_loss: 0.9929
Epoch 99/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1769 - val_loss: 1.0006
Epoch 100/100
225/225 [==============================] - 1s 3ms/step - loss: 0.1759 - val_loss: 1.0051

In [176]:
import sklearn.metrics as metrics

# predict on test data
y_pred = model.predict(X_test)

# evaluate the model
test_loss = model.evaluate(X_test, y_test, verbose=0)
accuracy = metrics.accuracy_score(y_test, y_pred.round())

print(f"Loss: {test_loss:.4f}, Accuracy: {accuracy*100:.2f}%")

71/71 [==============================] - 0s 2ms/step
Loss: 0.9971, Accuracy: 0.85%

In [160]:
y_pred = model.predict(X_test)
score = model.score(X_test, y_test, verbose=0)
score

71/71 [==============================] - 0s 3ms/step

AttributeError: 'Sequential' object has no attribute 'score'

In [179]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the input shape
input_shape = (1130,)

# Define the number of output classes
num_classes = 20

# Define the model
model = keras.Sequential([
    layers.Dense(512, activation='relu', input_shape=input_shape),
    layers.Dropout(0.2),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(num_classes, activation='softmax')
])

# Compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# Print the model summary
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_45 (Dense)            (None, 512)               579072

 dropout_9 (Dropout)         (None, 512)               0

 dense_46 (Dense)            (None, 256)               131328

 dropout_10 (Dropout)        (None, 256)               0

 dense_47 (Dense)            (None, 20)                5140

=================================================================
Total params: 715,540
Trainable params: 715,540
Non-trainable params: 0
_________________________________________________________________

In [180]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
225/225 [==============================] - 3s 10ms/step - loss: 569.4337 - accuracy: 0.0588 - val_loss: 542.5792 - val_accuracy: 0.0468
Epoch 2/10
225/225 [==============================] - 2s 10ms/step - loss: 5384.0547 - accuracy: 0.0483 - val_loss: 3074.9326 - val_accuracy: 0.0084
Epoch 3/10
225/225 [==============================] - 2s 9ms/step - loss: 14998.0488 - accuracy: 0.0479 - val_loss: 9025.5625 - val_accuracy: 0.0134
Epoch 4/10
225/225 [==============================] - 2s 9ms/step - loss: 26787.8926 - accuracy: 0.0540 - val_loss: 10505.4658 - val_accuracy: 0.1810
Epoch 5/10
225/225 [==============================] - 2s 9ms/step - loss: 40445.7891 - accuracy: 0.0494 - val_loss: 20277.7754 - val_accuracy: 0.0256
Epoch 6/10
225/225 [==============================] - 2s 9ms/step - loss: 53805.7500 - accuracy: 0.0551 - val_loss: 27778.9863 - val_accuracy: 0.0106
Epoch 7/10
225/225 [==============================] - 2s 9ms/step - loss: 66063.6094 - accuracy: 0.0542 - val_loss: 29451.2910 - val_accuracy: 0.1487
Epoch 8/10
225/225 [==============================] - 2s 10ms/step - loss: 77212.2812 - accuracy: 0.0490 - val_loss: 38101.3711 - val_accuracy: 0.0056
Epoch 9/10
225/225 [==============================] - 2s 10ms/step - loss: 85535.7500 - accuracy: 0.0492 - val_loss: 48320.0820 - val_accuracy: 0.0468
Epoch 10/10
225/225 [==============================] - 2s 9ms/step - loss: 92901.6562 - accuracy: 0.0505 - val_loss: 43790.7891 - val_accuracy: 0.0100