In [1]:
import glob
import numpy as np
csv_files = (glob.glob("C:/Users/Vishnu Kumar/Documents/IPL/raw/*info.csv")) 

import pandas as pd


df_append = pd.DataFrame()

for file in csv_files:
            df_temp = pd.read_csv(file,sep='漢ழ்字', engine='python',header=None)
            df_temp['ID'] = file
            df_temp = df_temp[(df_temp[0].str.startswith('info,toss_winner')) | (df_temp[0].str.startswith('info,toss_decision'))]
            df_append = pd.concat([df_append,df_temp])

df_append = df_append.reset_index()
df_append[['info', 'attrib','value']] = df_append[0].str.split(",", expand = True)
df_append = df_append.drop(columns=['index',0,'info'])
df_append['ID'] = df_append['ID'].str[40:-9]
toss_winner = df_append[df_append['attrib']=='toss_winner'].copy()
toss_decision = df_append[df_append['attrib']=='toss_decision'].copy()
toss_winner['ID'] = toss_winner['ID'].astype('int')
toss_decision['ID'] = toss_decision['ID'].astype('int')

all_matches = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")
# all_matches
all_matches = pd.merge(all_matches, toss_winner, how="left" ,left_on = "match_id", right_on = "ID" )
all_matches = all_matches.drop(columns=["ID", "attrib"])
all_matches = all_matches.rename(columns={"value": "toss_winner"})
all_matches = pd.merge(all_matches, toss_decision, how="left" ,left_on = "match_id", right_on = "ID" )
all_matches = all_matches.drop(columns=["ID", "attrib"])
all_matches = all_matches.rename(columns={"value": "toss_decision"})
all_matches = all_matches[all_matches['innings']<=2]
all_matches['season'] = all_matches['season'].replace(['2007/08', '2009', '2009/10', '2011' ,'2012','2018', '2019', '2020/21', '2021'], [2008,2009,2010,2011,2012,2018,2019,2020,2021])
all_matches['toss_win_batting'] = all_matches.apply(lambda x: 1 if x['toss_winner'] == x['batting_team'] else 0, axis=1)
all_matches['toss_decision'] = all_matches.apply(lambda x: 1 if x['toss_decision'] == 'bat' else 0, axis=1)
all_matches['player_dismissed'] = all_matches.apply(lambda x: 1 if x['player_dismissed'] == x['striker'] else 0, axis=1)
all_data = all_matches.copy()
# all_matches = pd.concat([all_matches, toss_winner], axis=1, join='outer', join_axes=[match_id,ID])

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\3567294720.py:25: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  all_matches = pd.read_csv("C:/Users/Vishnu Kumar/Documents/IPL/raw/all_matches.csv")

In [2]:
all_for_bowlers = all_data.copy()
all_for_bowlers['ball'] = (all_for_bowlers['ball'].apply(np.floor))+1
all_for_bowlers = all_for_bowlers.drop(columns=['start_date','striker','non_striker','runs_off_bat','extras','wides','noballs','byes','legbyes','penalty','wicket_type','player_dismissed','other_wicket_type','other_player_dismissed'])
all_for_bowlers['over1'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 1 else 0, axis=1)
all_for_bowlers['over2'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 2 else 0, axis=1)
all_for_bowlers['over3'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 3 else 0, axis=1)
all_for_bowlers['over4'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 4 else 0, axis=1)
all_for_bowlers['over5'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 5 else 0, axis=1)
all_for_bowlers['over6'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 6 else 0, axis=1)
all_for_bowlers['over7'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 7 else 0, axis=1)
all_for_bowlers['over8'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 8 else 0, axis=1)
all_for_bowlers['over9'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 9 else 0, axis=1)
all_for_bowlers['over10'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 10 else 0, axis=1)
all_for_bowlers['over11'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 11 else 0, axis=1)
all_for_bowlers['over12'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 12 else 0, axis=1)
all_for_bowlers['over13'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 13 else 0, axis=1)
all_for_bowlers['over14'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 14 else 0, axis=1)
all_for_bowlers['over15'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 15 else 0, axis=1)
all_for_bowlers['over16'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 16 else 0, axis=1)
all_for_bowlers['over17'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 17 else 0, axis=1)
all_for_bowlers['over18'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 18 else 0, axis=1)
all_for_bowlers['over19'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 19 else 0, axis=1)
all_for_bowlers['over20'] = all_for_bowlers.apply(lambda x: 1 if x['ball'] == 20 else 0, axis=1)
# all_for_bowlers

all_for_bowlers = pd.pivot_table(all_for_bowlers, values =['over1','over2','over3','over4','over5','over6','over7','over8','over9','over10','over11','over12','over13','over14','over15','over16','over17','over18','over19','over20'], index =['match_id', 'season','venue','innings','batting_team','bowling_team','bowler','toss_winner','toss_decision','toss_win_batting'], aggfunc = np.max).reset_index()
all_for_bowlers = pd.pivot_table(all_for_bowlers, values=['over1','over2','over3','over4','over5','over6','over7','over8','over9','over10','over11','over12','over13','over14','over15','over16','over17','over18','over19','over20'], index=['innings','bowler'], aggfunc=np.sum).reset_index()

innings_detail = pd.pivot_table(all_data,values='ball',index=['match_id','innings','bowling_team']).reset_index()
innings_detail = innings_detail.drop(columns = ['ball'])

df_append = pd.DataFrame()

for file in csv_files:
            df_temp = pd.read_csv(file,sep='漢ழ்字', engine='python',header=None)
            df_temp['ID'] = file
            df_temp = df_temp[(df_temp[0].str.startswith('info,player,'))]
            df_append = pd.concat([df_append,df_temp])
df_append = df_append.reset_index()
df_append[['info', 'play','team','player']] = df_append[0].str.split(",", expand = True)
df_append = df_append.drop(columns=['index',0,'info','play'])
df_append['ID'] = df_append['ID'].str[40:-9].astype('int')
player_list = pd.merge(df_append, innings_detail, how="left" ,left_on = ['ID','team'], right_on = ['match_id','bowling_team'] )
player_list = player_list.drop(columns=['match_id','bowling_team'])

player_list = pd.pivot_table(player_list, values='team', index=['player','innings'], aggfunc='count').reset_index()

all_for_bowlers = pd.merge(all_for_bowlers,player_list,how = 'left', left_on=['innings','bowler'], right_on=['innings','player'])

all_for_bowlers = all_for_bowlers.drop(columns=['player'])
all_for_bowlers = all_for_bowlers.rename(columns={"team": "no_of_matches"})
all_for_bowlers['over1'] = all_for_bowlers['over1']/all_for_bowlers['no_of_matches']
all_for_bowlers['over2'] = all_for_bowlers['over2']/all_for_bowlers['no_of_matches']
all_for_bowlers['over3'] = all_for_bowlers['over3']/all_for_bowlers['no_of_matches']
all_for_bowlers['over4'] = all_for_bowlers['over4']/all_for_bowlers['no_of_matches']
all_for_bowlers['over5'] = all_for_bowlers['over5']/all_for_bowlers['no_of_matches']
all_for_bowlers['over6'] = all_for_bowlers['over6']/all_for_bowlers['no_of_matches']
all_for_bowlers['over7'] = all_for_bowlers['over7']/all_for_bowlers['no_of_matches']
all_for_bowlers['over8'] = all_for_bowlers['over8']/all_for_bowlers['no_of_matches']
all_for_bowlers['over9'] = all_for_bowlers['over9']/all_for_bowlers['no_of_matches']
all_for_bowlers['over10'] = all_for_bowlers['over10']/all_for_bowlers['no_of_matches']
all_for_bowlers['over11'] = all_for_bowlers['over11']/all_for_bowlers['no_of_matches']
all_for_bowlers['over12'] = all_for_bowlers['over12']/all_for_bowlers['no_of_matches']
all_for_bowlers['over13'] = all_for_bowlers['over13']/all_for_bowlers['no_of_matches']
all_for_bowlers['over14'] = all_for_bowlers['over14']/all_for_bowlers['no_of_matches']
all_for_bowlers['over15'] = all_for_bowlers['over15']/all_for_bowlers['no_of_matches']
all_for_bowlers['over16'] = all_for_bowlers['over16']/all_for_bowlers['no_of_matches']
all_for_bowlers['over17'] = all_for_bowlers['over17']/all_for_bowlers['no_of_matches']
all_for_bowlers['over18'] = all_for_bowlers['over18']/all_for_bowlers['no_of_matches']
all_for_bowlers['over19'] = all_for_bowlers['over19']/all_for_bowlers['no_of_matches']
all_for_bowlers['over20'] = all_for_bowlers['over20']/all_for_bowlers['no_of_matches']
all_for_bowlers['overs_per_match'] = 0
for i in range(1, 21):
    all_for_bowlers['overs_per_match'] += all_for_bowlers[f'over{i}']

all_for_bowlers = all_for_bowlers[['innings','bowler', 'over1', 'over2', 'over3', 'over4', 'over5', 'over6', 'over7', 'over8', 'over9', 'over10', 'over11', 'over12', 'over13', 'over14', 'over15', 'over16', 'over17', 'over18', 'over19', 'over20', 'no_of_matches','overs_per_match']]

In [3]:
def has_element_frequency_more_than_4(tup):
    count = {}
    for item in tup:
        count[item] = count.get(item, 0) + 1
        if count[item] >= 4:
            return True
    return False

def has_consecutive_elements(tup):
    return any(a == b for a, b in zip(tup, tup[1:]))

def has_consecutive_numbers(t):
    return any(t[i] == t[i-1] + 1 for i in range(1, len(t)))

overs = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
import itertools
combinations = list(itertools.combinations(overs, 4))
filtered_lst = []
for tup in combinations:
    if has_consecutive_elements(tup)==False:
        if has_consecutive_numbers(tup)==False:
            filtered_lst.append(tup)
# remove_items = (-5, -3, -1)
# filtered_lst = [tuple(item for item in tup if item not in remove_items) for tup in filtered_lst]
filtered_lst = [tuple(item for item in tup if item) for tup in filtered_lst]
unique_tuples = []
for tup in filtered_lst:
    set_tup = set(tup)
    if set_tup not in unique_tuples:
        unique_tuples.append(set_tup)

filtered_lst = [tuple(set_tup) for set_tup in unique_tuples]

In [51]:
team1 = pd.read_excel("C:/Users/Vishnu Kumar/Documents/IPL/input/team1.xlsx")
team2 = pd.read_excel("C:/Users/Vishnu Kumar/Documents/IPL/input/team2.xlsx")
team1['bowl_innings'] = 2
team2['bowl_innings'] = 1

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():
C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

In [28]:
team1 = pd.merge(team1, all_for_bowlers, how = 'left', right_on = ['innings','bowler'] , left_on = ['bowl_innings', 'Team1'])
team1 = team1.dropna()
team1 = team1.drop(columns=['innings','Team1','no_of_matches'])
team1 = team1.sort_values(by=['overs_per_match'],ascending=False)
team1 = team1.reset_index()
team1 = team1.drop(columns=['index'])


my_list = team1['bowler'][0:5].to_numpy()

all_possible_bowler = pd.DataFrame(columns=['bowler', 'number_of_possibility'])


for i, val in enumerate(my_list):
    new_var_name = f"bowler_lst_{i}"
    locals()[new_var_name] = []
    bowler_average = team1[team1['bowler']==val]['overs_per_match'].iloc[0]
    bowler_average_max = round(bowler_average+0.5)
    bowler_average_min = round(bowler_average-0.5)
    if bowler_average_max>4:
        bowler_average_max = 4
        
    if bowler_average_min < 0:
        bowler_average_min =0

    bowler = val
    
    new_values = {1: team1.loc[team1['bowler'] == bowler, 'over1'].iloc[0], 
              2: team1.loc[team1['bowler'] == bowler, 'over2'].iloc[0], 
              3: team1.loc[team1['bowler'] == bowler, 'over3'].iloc[0],
              4: team1.loc[team1['bowler'] == bowler, 'over4'].iloc[0], 
              5: team1.loc[team1['bowler'] == bowler, 'over5'].iloc[0], 
              6: team1.loc[team1['bowler'] == bowler, 'over6'].iloc[0], 
              7: team1.loc[team1['bowler'] == bowler, 'over7'].iloc[0], 
              8: team1.loc[team1['bowler'] == bowler, 'over8'].iloc[0], 
              9: team1.loc[team1['bowler'] == bowler, 'over9'].iloc[0], 
              10: team1.loc[team1['bowler'] == bowler, 'over10'].iloc[0], 
              11: team1.loc[team1['bowler'] == bowler, 'over11'].iloc[0], 
              12: team1.loc[team1['bowler'] == bowler, 'over12'].iloc[0], 
              13: team1.loc[team1['bowler'] == bowler, 'over13'].iloc[0], 
              14: team1.loc[team1['bowler'] == bowler, 'over14'].iloc[0], 
              15: team1.loc[team1['bowler'] == bowler, 'over15'].iloc[0], 
              16: team1.loc[team1['bowler'] == bowler, 'over16'].iloc[0], 
              17: team1.loc[team1['bowler'] == bowler, 'over17'].iloc[0], 
              18: team1.loc[team1['bowler'] == bowler, 'over18'].iloc[0], 
              19: team1.loc[team1['bowler'] == bowler, 'over19'].iloc[0], 
              20: team1.loc[team1['bowler'] == bowler, 'over20'].iloc[0]}

    threshold = 0.15
    
    for tup in filtered_lst:
        flag = True
        for item in tup:
            if new_values[item] < threshold:
                flag = False
                break
        if flag:
            if len(tup)==4:
                locals()[new_var_name].append(tup)
                
    locals()[new_var_name] = [tuple(sorted(t)) for t in locals()[new_var_name]]
    all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
    locals()[new_var_name] = sorted(locals()[new_var_name], key=len, reverse=True)
    

    
all_possible_bowler = all_possible_bowler[all_possible_bowler['number_of_possibility']>0].reset_index()
result = pd.DataFrame(locals()[f"bowler_lst_{all_possible_bowler['index'][0]}"])
result = result.rename(columns={0:f"bowler_lst_{all_possible_bowler['index'][0]}_1",1:f"bowler_lst_{all_possible_bowler['index'][0]}_2",2:f"bowler_lst_{all_possible_bowler['index'][0]}_3",3:f"bowler_lst_{all_possible_bowler['index'][0]}_4"})

for i in range(1,len(all_possible_bowler)):
    
    bowler_lst_0 = pd.DataFrame(locals()[f"bowler_lst_{all_possible_bowler['index'][i]}"])
    bowler_lst_0 = bowler_lst_0.rename(columns={0:f"bowler_lst_{all_possible_bowler['index'][i]}_1",1:f"bowler_lst_{all_possible_bowler['index'][i]}_2",2:f"bowler_lst_{all_possible_bowler['index'][i]}_3",3:f"bowler_lst_{all_possible_bowler['index'][i]}_4"})

    result = pd.merge(result, bowler_lst_0, how="cross")
    print(i)
    duplicate_mask = result.apply(lambda row: len(set(row)) == len(row), axis=1)
    result = result[duplicate_mask]
    print(i)

    
first_bowling_order = result.copy()
first_bowling_order = first_bowling_order.reset_index()
first_bowling_order = first_bowling_order.drop(columns=['index'])
first_bowling_order = first_bowling_order.reset_index()
first_bowling_order = first_bowling_order.melt(id_vars=['index'],var_name='bowler', value_name='over')

# first_bowling_order_new
first_bowling_order = pd.pivot_table(first_bowling_order, index='index',values = 'bowler', columns='over', aggfunc=min)

# Define a lambda function to remove last two characters from a string
remove_last_two = lambda x: x[11] if isinstance(x, str) and len(x) >= 12 else x

# Apply the function to every cell in the dataframe using applymap()
first_bowling_order = first_bowling_order.applymap(remove_last_two)

first_bowling_order = first_bowling_order.astype(int)


import math

new_my_list = team1['bowler'][5:].to_numpy()

temporary_bowl_order1 = first_bowling_order.sample(frac = 0)

for i, val in enumerate(new_my_list):
    
    
    temp_pd = team1[team1['bowler']==val].T.reset_index()[2:22]
    temp_pd = temp_pd.rename(columns={ temp_pd.columns[1]: "bowl_prob" })
    temp_pd['index'] = temp_pd['index'].replace('over', "", regex=True)
    temp_pd['index'] = temp_pd['index'].astype('int')
    
    if (temp_pd['bowl_prob'].sum())>0 and (temp_pd['bowl_prob'].sum())<0.5 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.025)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.025)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.025)
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        first_bowling_order = pd.concat([first_bowling_order,temporary_bowl_order1])
        
    if (temp_pd['bowl_prob'].sum())>=0.5 and (temp_pd['bowl_prob'].sum())<=1 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.05)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.05)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.05)
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        first_bowling_order = pd.concat([first_bowling_order,temporary_bowl_order1])
        
    if (temp_pd['bowl_prob'].sum())>1 and (temp_pd['bowl_prob'].sum())<=2 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        consecutive = (temp_pd['index'] - temp_pd['index'].shift(1)) == 1
        temp_pd = temp_pd.loc[~consecutive]
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])        
        temporary_bowl_order = first_bowling_order.sample(frac = 0.1)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.1)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        first_bowling_order = pd.concat([first_bowling_order,temporary_bowl_order1])

    if (temp_pd['bowl_prob'].sum())>2 and (temp_pd['bowl_prob'].sum())<=3 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        consecutive = (temp_pd['index'] - temp_pd['index'].shift(1)) == 1
        temp_pd = temp_pd.loc[~consecutive]
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])        
        temporary_bowl_order = first_bowling_order.sample(frac = 0.15)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = first_bowling_order.sample(frac = 0.15)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order[temp_pd.iat[3,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
            
        first_bowling_order = pd.concat([first_bowling_order,temporary_bowl_order1])

team1 = team1.reset_index()
first_bowling_order = first_bowling_order.replace( team1.set_index('index')['bowler'].to_dict())
first_bowling_order = first_bowling_order.reset_index()
first_bowling_order = first_bowling_order.drop(columns=['index'])

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\286748065.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\286748065.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\286748065.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\286748065.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\286748065.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)

1
1
2
2
3
3
4
4

In [52]:
team2 = pd.merge(team2, all_for_bowlers, how = 'left', right_on = ['innings','bowler'] , left_on = ['bowl_innings', 'Team2'])
team2 = team2.dropna()
team2 = team2.drop(columns=['innings','Team2','no_of_matches'])
team2 = team2.sort_values(by=['overs_per_match'],ascending=False)
team2 = team2.reset_index()
team2 = team2.drop(columns=['index'])


my_list = team2['bowler'][0:5].to_numpy()

all_possible_bowler = pd.DataFrame(columns=['bowler', 'number_of_possibility'])


for i, val in enumerate(my_list):
    new_var_name = f"bowler_lst_{i}"
    locals()[new_var_name] = []
    bowler_average = team2[team2['bowler']==val]['overs_per_match'].iloc[0]
    bowler_average_max = round(bowler_average+0.5)
    bowler_average_min = round(bowler_average-0.5)
    if bowler_average_max>4:
        bowler_average_max = 4
        
    if bowler_average_min < 0:
        bowler_average_min =0

    bowler = val
    
    new_values = {1: team2.loc[team2['bowler'] == bowler, 'over1'].iloc[0], 
              2: team2.loc[team2['bowler'] == bowler, 'over2'].iloc[0], 
              3: team2.loc[team2['bowler'] == bowler, 'over3'].iloc[0],
              4: team2.loc[team2['bowler'] == bowler, 'over4'].iloc[0], 
              5: team2.loc[team2['bowler'] == bowler, 'over5'].iloc[0], 
              6: team2.loc[team2['bowler'] == bowler, 'over6'].iloc[0], 
              7: team2.loc[team2['bowler'] == bowler, 'over7'].iloc[0], 
              8: team2.loc[team2['bowler'] == bowler, 'over8'].iloc[0], 
              9: team2.loc[team2['bowler'] == bowler, 'over9'].iloc[0], 
              10: team2.loc[team2['bowler'] == bowler, 'over10'].iloc[0], 
              11: team2.loc[team2['bowler'] == bowler, 'over11'].iloc[0], 
              12: team2.loc[team2['bowler'] == bowler, 'over12'].iloc[0], 
              13: team2.loc[team2['bowler'] == bowler, 'over13'].iloc[0], 
              14: team2.loc[team2['bowler'] == bowler, 'over14'].iloc[0], 
              15: team2.loc[team2['bowler'] == bowler, 'over15'].iloc[0], 
              16: team2.loc[team2['bowler'] == bowler, 'over16'].iloc[0], 
              17: team2.loc[team2['bowler'] == bowler, 'over17'].iloc[0], 
              18: team2.loc[team2['bowler'] == bowler, 'over18'].iloc[0], 
              19: team2.loc[team2['bowler'] == bowler, 'over19'].iloc[0], 
              20: team2.loc[team2['bowler'] == bowler, 'over20'].iloc[0]}

    threshold = 0.15
    
    for tup in filtered_lst:
        flag = True
        for item in tup:
            if new_values[item] < threshold:
                flag = False
                break
        if flag:
            if len(tup)==4:
                locals()[new_var_name].append(tup)
                
    locals()[new_var_name] = [tuple(sorted(t)) for t in locals()[new_var_name]]
    all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
    locals()[new_var_name] = sorted(locals()[new_var_name], key=len, reverse=True)
    

    
all_possible_bowler = all_possible_bowler[all_possible_bowler['number_of_possibility']>0].reset_index()
result = pd.DataFrame(locals()[f"bowler_lst_{all_possible_bowler['index'][0]}"])
result = result.rename(columns={0:f"bowler_lst_{all_possible_bowler['index'][0]}_1",1:f"bowler_lst_{all_possible_bowler['index'][0]}_2",2:f"bowler_lst_{all_possible_bowler['index'][0]}_3",3:f"bowler_lst_{all_possible_bowler['index'][0]}_4"})

for i in range(1,len(all_possible_bowler)):
    
    bowler_lst_0 = pd.DataFrame(locals()[f"bowler_lst_{all_possible_bowler['index'][i]}"])
    bowler_lst_0 = bowler_lst_0.rename(columns={0:f"bowler_lst_{all_possible_bowler['index'][i]}_1",1:f"bowler_lst_{all_possible_bowler['index'][i]}_2",2:f"bowler_lst_{all_possible_bowler['index'][i]}_3",3:f"bowler_lst_{all_possible_bowler['index'][i]}_4"})

    result = pd.merge(result, bowler_lst_0, how="cross")
    print(i)
    duplicate_mask = result.apply(lambda row: len(set(row)) == len(row), axis=1)
    result = result[duplicate_mask]
    print(i)

    
second_bowling_order = result.copy()
second_bowling_order = second_bowling_order.reset_index()
second_bowling_order = second_bowling_order.drop(columns=['index'])
second_bowling_order = second_bowling_order.reset_index()
second_bowling_order = second_bowling_order.melt(id_vars=['index'],var_name='bowler', value_name='over')

# second_bowling_order_new
second_bowling_order = pd.pivot_table(second_bowling_order, index='index',values = 'bowler', columns='over', aggfunc=min)

# Define a lambda function to remove last two characters from a string
remove_last_two = lambda x: x[11] if isinstance(x, str) and len(x) >= 12 else x

# Apply the function to every cell in the dataframe using applymap()
second_bowling_order = second_bowling_order.applymap(remove_last_two)

second_bowling_order = second_bowling_order.astype(int)


import math

new_my_list = team2['bowler'][5:].to_numpy()

temporary_bowl_order1 = second_bowling_order.sample(frac = 0)

for i, val in enumerate(new_my_list):
    
    
    temp_pd = team2[team2['bowler']==val].T.reset_index()[2:22]
    temp_pd = temp_pd.rename(columns={ temp_pd.columns[1]: "bowl_prob" })
    temp_pd['index'] = temp_pd['index'].replace('over', "", regex=True)
    temp_pd['index'] = temp_pd['index'].astype('int')
    
    if (temp_pd['bowl_prob'].sum())>0 and (temp_pd['bowl_prob'].sum())<0.5 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.025)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.025)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.025)
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        second_bowling_order = pd.concat([second_bowling_order,temporary_bowl_order1])
        
    if (temp_pd['bowl_prob'].sum())>=0.5 and (temp_pd['bowl_prob'].sum())<=1 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.05)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.05)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.05)
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        second_bowling_order = pd.concat([second_bowling_order,temporary_bowl_order1])
        
    if (temp_pd['bowl_prob'].sum())>1 and (temp_pd['bowl_prob'].sum())<=2 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        consecutive = (temp_pd['index'] - temp_pd['index'].shift(1)) == 1
        temp_pd = temp_pd.loc[~consecutive]
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])        
        temporary_bowl_order = second_bowling_order.sample(frac = 0.1)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.1)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        second_bowling_order = pd.concat([second_bowling_order,temporary_bowl_order1])

    if (temp_pd['bowl_prob'].sum())>2 and (temp_pd['bowl_prob'].sum())<=3 :
        temp_pd = temp_pd.sort_values(by=['bowl_prob'], ascending = False)
        consecutive = (temp_pd['index'] - temp_pd['index'].shift(1)) == 1
        temp_pd = temp_pd.loc[~consecutive]
        temp_pd = temp_pd.reset_index()
        temp_pd = temp_pd.drop(columns=['level_0'])        
        temporary_bowl_order = second_bowling_order.sample(frac = 0.15)
        temporary_bowl_order[temp_pd.iat[0,0]] = i+5
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
        temporary_bowl_order = second_bowling_order.sample(frac = 0.15)
        temporary_bowl_order[temp_pd.iat[1,0]] = i+5
        temporary_bowl_order[temp_pd.iat[2,0]] = i+5
        temporary_bowl_order[temp_pd.iat[3,0]] = i+5
        temporary_bowl_order1 = pd.concat([temporary_bowl_order1, temporary_bowl_order])
            
        second_bowling_order = pd.concat([second_bowling_order,temporary_bowl_order1])

team2 = team2.reset_index()
second_bowling_order = second_bowling_order.replace( team2.set_index('index')['bowler'].to_dict())
second_bowling_order = second_bowling_order.reset_index()
second_bowling_order = second_bowling_order.drop(columns=['index'])

C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\1179038311.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\1179038311.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\1179038311.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\1179038311.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)
C:\Users\Vishnu Kumar\AppData\Local\Temp\ipykernel_13856\1179038311.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  all_possible_bowler = all_possible_bowler.append({'bowler': val, 'number_of_possibility': len(locals()[new_var_name])}, ignore_index=True)

1
1
2
2
3
3
4
4

In [53]:
second_bowling_order

over,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Rashid Khan,Mohammed Shami,Rashid Khan,LH Ferguson,Rashid Khan,R Sai Kishore,Rashid Khan,Yash Dayal,R Sai Kishore,LH Ferguson,Mohammed Shami,R Sai Kishore,LH Ferguson,R Sai Kishore,Yash Dayal,LH Ferguson
1,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Rashid Khan,Mohammed Shami,Rashid Khan,R Sai Kishore,Rashid Khan,LH Ferguson,Rashid Khan,Yash Dayal,R Sai Kishore,LH Ferguson,Mohammed Shami,R Sai Kishore,LH Ferguson,R Sai Kishore,Yash Dayal,LH Ferguson
2,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Rashid Khan,Mohammed Shami,Rashid Khan,LH Ferguson,Rashid Khan,R Sai Kishore,Rashid Khan,Yash Dayal,R Sai Kishore,LH Ferguson,Mohammed Shami,R Sai Kishore,LH Ferguson,R Sai Kishore,LH Ferguson,Yash Dayal
3,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Rashid Khan,Mohammed Shami,Rashid Khan,R Sai Kishore,Rashid Khan,LH Ferguson,Rashid Khan,Yash Dayal,R Sai Kishore,LH Ferguson,Mohammed Shami,R Sai Kishore,LH Ferguson,R Sai Kishore,LH Ferguson,Yash Dayal
4,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Rashid Khan,Mohammed Shami,Rashid Khan,LH Ferguson,Rashid Khan,LH Ferguson,Rashid Khan,R Sai Kishore,Yash Dayal,R Sai Kishore,Mohammed Shami,R Sai Kishore,LH Ferguson,R Sai Kishore,Yash Dayal,LH Ferguson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14158,Mohammed Shami,Yash Dayal,Mohammed Shami,LH Ferguson,Rashid Khan,Mohammed Shami,LH Ferguson,R Sai Kishore,HH Pandya,R Sai Kishore,Rashid Khan,R Sai Kishore,Yash Dayal,LH Ferguson,Rashid Khan,HH Pandya,Yash Dayal,Mohammed Shami,LH Ferguson,Yash Dayal
14159,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Rashid Khan,Mohammed Shami,Rashid Khan,R Sai Kishore,HH Pandya,LH Ferguson,R Sai Kishore,Rashid Khan,Yash Dayal,LH Ferguson,R Sai Kishore,HH Pandya,LH Ferguson,R Sai Kishore,LH Ferguson,Yash Dayal
14160,Mohammed Shami,Yash Dayal,Mohammed Shami,LH Ferguson,Yash Dayal,Mohammed Shami,Rashid Khan,LH Ferguson,HH Pandya,LH Ferguson,R Sai Kishore,Rashid Khan,R Sai Kishore,LH Ferguson,R Sai Kishore,HH Pandya,Yash Dayal,Rashid Khan,Yash Dayal,Mohammed Shami
14161,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,Mohammed Shami,LH Ferguson,Rashid Khan,LH Ferguson,HH Pandya,LH Ferguson,R Sai Kishore,Rashid Khan,Yash Dayal,R Sai Kishore,Rashid Khan,HH Pandya,Mohammed Shami,R Sai Kishore,LH Ferguson,Yash Dayal
14162,Mohammed Shami,Yash Dayal,Mohammed Shami,Yash Dayal,LH Ferguson,Mohammed Shami,Rashid Khan,LH Ferguson,HH Pandya,LH Ferguson,R Sai Kishore,Yash Dayal,R Sai Kishore,Rashid Khan,R Sai Kishore,HH Pandya,Mohammed Shami,R Sai Kishore,LH Ferguson,Yash Dayal

In [54]:
first_bowling_order

over,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,TA Boult,M Prasidh Krishna,TA Boult,OC McCoy,TA Boult,YS Chahal,OC McCoy,R Ashwin,YS Chahal,R Ashwin,YS Chahal,R Ashwin,TA Boult,YS Chahal,R Ashwin,M Prasidh Krishna,OC McCoy,M Prasidh Krishna,OC McCoy,M Prasidh Krishna
1,TA Boult,M Prasidh Krishna,TA Boult,OC McCoy,TA Boult,YS Chahal,OC McCoy,R Ashwin,YS Chahal,R Ashwin,YS Chahal,R Ashwin,TA Boult,R Ashwin,YS Chahal,M Prasidh Krishna,OC McCoy,M Prasidh Krishna,OC McCoy,M Prasidh Krishna
2,TA Boult,M Prasidh Krishna,TA Boult,OC McCoy,TA Boult,R Ashwin,OC McCoy,YS Chahal,R Ashwin,YS Chahal,R Ashwin,YS Chahal,TA Boult,YS Chahal,R Ashwin,M Prasidh Krishna,OC McCoy,M Prasidh Krishna,OC McCoy,M Prasidh Krishna
3,TA Boult,M Prasidh Krishna,TA Boult,OC McCoy,TA Boult,M Prasidh Krishna,OC McCoy,YS Chahal,R Ashwin,YS Chahal,R Ashwin,YS Chahal,TA Boult,R Ashwin,YS Chahal,R Ashwin,OC McCoy,M Prasidh Krishna,OC McCoy,M Prasidh Krishna
4,TA Boult,M Prasidh Krishna,TA Boult,OC McCoy,TA Boult,R Ashwin,OC McCoy,YS Chahal,R Ashwin,YS Chahal,R Ashwin,YS Chahal,TA Boult,R Ashwin,YS Chahal,M Prasidh Krishna,OC McCoy,M Prasidh Krishna,OC McCoy,M Prasidh Krishna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25424,TA Boult,M Prasidh Krishna,TA Boult,M Prasidh Krishna,R Ashwin,M Prasidh Krishna,YS Chahal,OC McCoy,YS Chahal,OC McCoy,YS Chahal,R Ashwin,YS Chahal,R Ashwin,OC McCoy,R Ashwin,TA Boult,M Prasidh Krishna,YBK Jaiswal,TA Boult
25425,TA Boult,M Prasidh Krishna,R Ashwin,M Prasidh Krishna,TA Boult,YS Chahal,OC McCoy,R Ashwin,OC McCoy,YS Chahal,OC McCoy,YS Chahal,TA Boult,R Ashwin,YS Chahal,R Ashwin,M Prasidh Krishna,TA Boult,YBK Jaiswal,M Prasidh Krishna
25426,R Ashwin,M Prasidh Krishna,TA Boult,R Ashwin,M Prasidh Krishna,YS Chahal,R Ashwin,OC McCoy,YS Chahal,OC McCoy,YS Chahal,R Ashwin,TA Boult,YS Chahal,OC McCoy,TA Boult,OC McCoy,M Prasidh Krishna,YBK Jaiswal,M Prasidh Krishna
25427,TA Boult,M Prasidh Krishna,R Ashwin,M Prasidh Krishna,TA Boult,M Prasidh Krishna,YS Chahal,OC McCoy,YS Chahal,R Ashwin,YS Chahal,R Ashwin,OC McCoy,R Ashwin,YS Chahal,TA Boult,OC McCoy,M Prasidh Krishna,YBK Jaiswal,OC McCoy
25428,TA Boult,M Prasidh Krishna,R Ashwin,M Prasidh Krishna,TA Boult,YS Chahal,OC McCoy,R Ashwin,YS Chahal,OC McCoy,YS Chahal,R Ashwin,TA Boult,R Ashwin,OC McCoy,YS Chahal,M Prasidh Krishna,TA Boult,YBK Jaiswal,M Prasidh Krishna